#!/bin/sh

# Runs dig on a list of domain names.
# Requires dig; use 'pacman -S bind'
# if you need to install dig.

# This file is the list of domain names.
Domains="$HOME/domains.txt"

# This is the path the output will be saved to.
Outpath="$HOME/.digger"

# Run dig against these types of records.
RecordTypes="any
ns
a
mx
srv
txt
x"

# The files generated by this script will include the date.
Output="$(date +%Y_%b_%d).txt"

DigLines=$(cat $Domains)
for Line in $DigLines
do
	for Type in $RecordTypes
	do
		mkdir -p "$Outpath/$Line"
		cd "$Outpath/$Line"
		echo "=== Record type: $Type ===" >> $Output
		dig $Type $Line +noall +answer >> "$Output"
		echo "--- End of record type: $Type ===" >> $Output
	done
done
